[logging]
level = DEBUG

[audio]
enabled = true
success = sounds/happy_wheels_victory.wav
camera_error = sounds/camera_error.wav
solver_error = sounds/solver_error.wav
coordinate_mapper_error = sounds/coordinate_mapper_error.wav
microcontroller_error = sounds/microcontroller_error.wav
unexpected_error = sounds/unexpected_error.wav

[audio.error_sounds]
camera.CameraConnectionError = sounds/gopro_connection_error.wav
camera.ArucoMarkersError = sounds/aruco_not_found.wav
; solver.ValueError = data/sounds/solver_bad_input.wav
microcontroller.TimeoutError = sounds/microcontroller_connection_timeout.wav
; default = data/sounds/generic_error.wav

[microcontroller]
transport = stub

[uart]
port = /dev/serial0
baudrate = 57600
timeout_seconds = 0.2
ack_timeout_seconds = 1.0
done_timeout_seconds = 30.0
wait_for_start = false

[camera]
transport = mock
mock_image = data/realistic_images/GOPR0357_flattened.JPG
; mock_image = data/realistic_images/GOPR0412_flattened.JPG
; mock_image = data/pren1_samples/simple_1_rotated.png
; mock_image = data/pren1_samples/round_edges_2.png
; mock_image = data/pren1_samples/not_so_simple.png
; mock_image = data/pren1_samples/heavy.png
; mock_image = data/pren1_samples/dumb_corners.png
; mock_image = data/pren1_samples/less_simple_1_rotated.png

[coordinate_mapper]
scale_x = 23.7
scale_y = 23.7
auto_calculate_scale = true
base_plate_width_mm = 295
base_plate_height_mm = 208
steps_per_mm = 80.0

[coordinate_mapper.start]
x_min = 14500.0
y_min = -2400.0

[coordinate_mapper.end]
y_min = 5600.0
x_min = 26032

[solver]
algorithm = brute_force
min_area = 60000
threshold = none
piece_margin = 10.0
corner_simplify_frac = 0.004
